### ISSUE TITLE
Provide easier access to distinct users - api

### ISSUE THREAD

**Issue by scotch-soda-game** [scotch-soda-game/Edu-Kart-E-Commerece#1]
Introduce a novel functionality enabling users to access distinct features, while ensuring roles are assigned accordingly.

I would be amazing if you work on this issue and give some attention to DTO's too.

**Comment by tihal-dipanshu** [comment]
Assign this to me, I'll start working on this.

**Comment by scotch-soda-game** [comment]
Great Job!, this issue if fixed now.
